version: '2.1'

services:

  postgres_image:
    image: postgres:latest
    restart: always
    ports:
     - 5433:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "hortex"
      POSTGRES_DB: "BitchPlease"
    networks:
     - mynetwork
    volumes:
     - pgdata:/var/lib/postgresql/data

  dockerapi:
    image: dockerapi:latest
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres_image
    depends_on:
      - "postgres_image"
    networks:
      - mynetwork  
  
volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge 